owner: GoofyGoofsterClub
repo: status.uwu.so

sites:
  - name: uwu.so
    url: https://uwu.so

status-website:
  cname: status.uwu.so
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.uwu.so
  introTitle: "**uwu.so** is a free open-source file hosting service."
  introMessage: Welcome
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/LMNYX/imagination-server
